"""The rule walk: a Reegel page that teaches by doing (ADR-0009 step 2).

Four steps and a switch, for a topic that has a walk in `lessontext.WALKS`:

- **notice** — two to four sentences with the word to notice underlined and
  not yet named, and a question built from a template that names the forms and
  states no rule;
- **ask** — one item per entry of the walk's spec, generated by the topic's
  own generator at run time and keyed by it; the page offers the key and the
  generator's other form, and the answer goes to `/api/practice/answer`, which
  grades it from the signed item;
- **explain** — at most `MAX_WORDS` words in the explanation language from one
  cited section, the one text a model wrote, refused here unless every Estonian
  word in it is code's or the cited source's (`problems`);
- **contrast** — a wrong/right pair: a frame with the generator's other form
  and its key;
- **the switch** — one condition at a time; the sentence changes and the
  word's form line says what the form is.

Nothing here writes Estonian. A sentence is a generator frame filled with a
Vabamorf form (`drills.TEMPLATES`, `existential.FRAMES`) or a sentence quoted in
the topic's sourced points; a form is named from its Vabamorf tag, as the drills
name it. A sentence code cannot resolve — a frame the generator does not have, a
noun outside its pool, a form Vabamorf cannot give uniquely, a quote the source
does not print — is left out, and a step with nothing left is empty.
"""

from __future__ import annotations

import re
import secrets

from .item import BLANK
from .morph import _readings, unique_form

#: The explain step's length, in words of the explanation language.
MAX_WORDS = 40

#: Case names as EKK and the exam use them, from Vabamorf's tag.
_CASE = {"n": "nimetav", "g": "omastav", "p": "osastav"}

#: One Russian gloss per case name, the same as the page's own list (`FORM_RU`
#: in `core.js`) and the topic points' "omastav (родительный падеж)".
CASE_RU = {"nimetav": "именительный падеж", "omastav": "родительный падеж",
           "osastav": "частичный падеж"}

#: Estonian words in prose: the tutor's own pattern, so both gates read the
#: same words.
_WORD = re.compile(r"[A-Za-zÀ-ÿŠŽšžÕÄÖÜõäöü][A-Za-zÀ-ÿŠŽšžÕÄÖÜõäöü-]{2,}")

#: A sentence ends at `.`, `!` or `?` followed by a space and a capital, a
#: quote or markup: `ед. ч. при` and `где? (*käisin*` run on.
_SENTENCE_END = re.compile(r"(?<=[.!?])\s+(?=[*«A-ZА-ЯЁÕÄÖÜŠŽ])")


def gist(summary_ru: str | None, least: int = 6) -> str | None:
    """The page's one-line rule: the first sentence of the topic's sourced
    summary, with the next ones while it is shorter than `least` words
    (`Настоящее время.` alone says nothing)."""
    if not summary_ru or not summary_ru.strip():
        return None
    taken: list[str] = []
    for part in _SENTENCE_END.split(summary_ru.strip()):
        taken.append(part)
        if _words(" ".join(taken)) >= least:
            break
    return " ".join(taken)


def _words(text: str) -> int:
    return sum(1 for w in text.split() if any(ch.isalnum() for ch in w))


def form_name(tag: str) -> str | None:
    """`sg g` → `omastav`, `pl n` → `mitmuse nimetav`: what the drills call it."""
    number, _, case = tag.partition(" ")
    name = _CASE.get(case)
    if name is None or number not in ("sg", "pl"):
        return None
    return f"mitmuse {name}" if number == "pl" else name


def form_ru(name: str) -> str:
    case = name.removeprefix("mitmuse ")
    gloss = CASE_RU.get(case, "")
    return f"{gloss}, мн. ч." if gloss and name != case else gloss


# --------------------------------------------------------------------------
# Sentences: a generator frame and a noun, or a quote from the source
# --------------------------------------------------------------------------

def _frames(topic: str) -> list[tuple[str, str, frozenset[str], str, str]]:
    """The topic generator's frames as (frame with BLANK, rule, nouns it takes,
    tag of its key, tag of the other form it is drilled against)."""
    if topic == "obj-case":
        from .drills import POOLS, TEMPLATES, _TAG

        return [(t.frame.format(obj=BLANK), t.rule, frozenset(POOLS[t.pool]),
                 _TAG[(t.case, t.number)], _TAG[(t.other, t.number)])
                for t in TEMPLATES]
    if topic == "osaalus":
        from .existential import FRAMES

        return [(f.text, f.rule, frozenset(f.nouns), f.answer, f.against) for f in FRAMES]
    return []


def _source_text(topic: str) -> str:
    """What the topic's cited sources say, as the repository holds them: its EKK
    summary and its written points."""
    from .curriculum import by_id
    from .lessontext import LESSONS

    ref = by_id(topic).reference
    text = LESSONS.get(topic)
    return "\n".join([ref.summary_ru if ref else "", *(text.points_ru if text else ())])


def _cased(prompt: str, form: str) -> tuple[str, str, str]:
    before, after = prompt.split(BLANK)
    # A form that opens the sentence is capitalised, as `item.fill` does.
    return before, (form[:1].upper() + form[1:]) if not before else form, after


def sentence(topic: str, s) -> dict | None:
    """One walk sentence resolved by code, or None when code cannot vouch for it.

    The result has the sentence around the word (`before`, `form`, `after`),
    the word's lemma, Vabamorf tag, name and gloss, and for a frame the other
    form the generator drills it against (`wrong`)."""
    if s.quote:
        return _quoted(topic, s)
    found = [f for f in _frames(topic) if f[0] == s.frame and f[1] == s.rule]
    if len(found) != 1 or s.noun not in found[0][2]:
        return None
    _frame, _rule, _nouns, tag, against = found[0]
    form, wrong = unique_form(s.noun, tag), unique_form(s.noun, against)
    name = form_name(tag)
    if not form or not wrong or form == wrong or not name:
        return None
    before, shown, after = _cased(s.frame, form)
    return {"before": before, "form": shown, "after": after, "lemma": s.noun,
            "tag": tag, "name": name, "form_ru": form_ru(name),
            "wrong": wrong, "wrong_tag": against, "source": ""}


def _quoted(topic: str, s) -> dict | None:
    """A sentence quoted in the topic's sourced points, with the word it is about.
    The quote must be there verbatim, the word must be one word of it, and
    Vabamorf must read that word one way only in the tag given."""
    if s.quote not in _source_text(topic):
        return None
    words = re.findall(r"\w+", s.quote)
    if words.count(s.form) != 1:
        return None
    lemmas = {lemma for lemma, tag in _readings(s.form) if tag == s.tag}
    name = form_name(s.tag)
    if len(lemmas) != 1 or not name:
        return None
    lemma = lemmas.pop()
    if unique_form(lemma, s.tag) != s.form:
        return None
    at = re.search(rf"\b{re.escape(s.form)}\b", s.quote)
    from .curriculum import by_id

    ref = by_id(topic).reference
    return {"before": s.quote[:at.start()], "form": s.form,
            "after": s.quote[at.end():] + ".", "lemma": lemma, "tag": s.tag,
            "name": name, "form_ru": form_ru(name),
            "source": f"EKK {ref.ekk_section}" if ref else ""}


# --------------------------------------------------------------------------
# The ask step: items from the topic's generator, keyed by it
# --------------------------------------------------------------------------

def _ask(topic: str, spec: tuple[tuple[str, ...], ...], seed: int, words) -> list[dict]:
    """One item per entry, each a one-item practice set the server can issue
    again from its ref (`itemref.regenerate`), so the answer is graded against
    what was issued. The page gets the two forms to choose from, not which is
    the key."""
    from . import practice
    from .config import LEVELS
    from .itemref import practice_ref, sign

    out, seen = [], set()
    for i, rules in enumerate(spec):
        for attempt in range(8):
            at = (seed + 7919 * i + 104729 * attempt) % 2**31
            try:
                found = practice.items_for(topic, count=1, levels=LEVELS, seed=at, rules=rules)
            except (ValueError, RuntimeError, KeyError):
                found = []
            if not found:
                break
            item = found[0]
            if item.prompt in seen or item.prompt.count(BLANK) != 1:
                continue
            seen.add(item.prompt)
            before, after = item.prompt.split(BLANK)
            out.append({
                "topic": topic, "rule": item.rule, "prompt": item.prompt,
                "before": before, "after": after, "lemma": item.lemma,
                "lemma_ru": _meaning(words, item.lemma),
                "choices": sorted({item.answer, item.distractor}),
                "form_after": item.label, "form_ru": form_ru(item.label),
                "token": sign(item, practice_ref(
                    topic, seed=at, count=1, levels=LEVELS, theme=None,
                    rules=rules, index=0)),
            })
            break
    return out


def _meaning(words, lemma: str) -> str:
    """The lemma's Russian from local tables only, for the line under the gap."""
    if words is None:
        return ""
    from .meaning import russian

    try:
        found, _ = russian(words, lemma)
    except Exception:  # noqa: BLE001 - a missing gloss never costs the item
        return ""
    return ", ".join(found[:2])


# --------------------------------------------------------------------------
# The explain step: a model's words, held to code and the cited source
# --------------------------------------------------------------------------

def _terms(topic: str) -> set[str]:
    """Estonian words that name grammar rather than being forms: the topic's
    name, its rule's term, the case names, the walk's condition labels, the
    handbook's abbreviation."""
    from .curriculum import by_id
    from .lessons import CASES
    from .lessontext import WALKS

    t = by_id(topic)
    said = [t.et, t.reference.et_term if t.reference else ""]
    said += [name for name, _ in CASES]
    spec = WALKS.get(topic)
    if spec:
        said += [c.et for c in (*spec.switch, *spec.contrast)]
    return {w.casefold() for w in _WORD.findall(" ".join(said))} | {"ekk"}


def _grounds(topic: str, built: list[dict]) -> set[str]:
    """Every Estonian word the walk may say: its sentences and forms, the
    cited source's own words, and the grammar terms."""
    said = [_source_text(topic)]
    for s in built:
        said += [s["before"], s["form"], s["after"], s.get("wrong", "")]
    return {w.casefold() for w in _WORD.findall(" ".join(said))} | _terms(topic)


def check_prose(text: str, *, allowed: set[str], terms: set[str]) -> list[str]:
    """What is wrong with a model's paragraph, or nothing.

    Gate one: every Estonian word is in `allowed` (code's or the cited
    source's). Gate two, `tutor._grounded`: every word that is not a grammar
    term is one Vabamorf knows — a non-word that reached `allowed` still fails.
    """
    from .tutor import _grounded

    found = [f"«{w}» не из кода и не из источника"
             for w in dict.fromkeys(_WORD.findall(text)) if w.casefold() not in allowed]
    if not _grounded(text, terms):
        found.append("в тексте есть слово, которого Vabamorf не знает")
    if _words(text) > MAX_WORDS:
        found.append(f"длиннее {MAX_WORDS} слов")
    return found


def problems(topic: str) -> list[str]:
    """Why the topic's explanation would be refused, or nothing."""
    from .lessontext import WALKS

    spec = WALKS.get(topic)
    if spec is None:
        return []
    built = [s for s in (sentence(topic, x) for x in _every_sentence(spec)) if s]
    return check_prose(spec.explain.text_ru, allowed=_grounds(topic, built),
                       terms=_terms(topic))


def _every_sentence(spec):
    return [*spec.notice, *(c.sentence for c in (*spec.contrast, *spec.switch))]


def _explain(topic: str, spec, built: list[dict]) -> dict | None:
    from .lessontext import LESSONS

    e = spec.explain
    if check_prose(e.text_ru, allowed=_grounds(topic, built), terms=_terms(topic)):
        return None
    label = f"EKK {e.section}"
    source = next((s for s in LESSONS[topic].sources if s.label == label), None)
    if source is None:
        return None
    return {"id": e.id, "lang": "ru", "text": e.text_ru, "words": _words(e.text_ru),
            "section": e.section, "source": {"label": source.label, "url": source.url},
            "engine": e.engine, "written": e.written}


# --------------------------------------------------------------------------
# The walk
# --------------------------------------------------------------------------

def _question(forms: list[str]) -> str:
    """The notice step's question: the forms, and no rule."""
    marked = [f"*{f}*" for f in forms]
    return f"Почему {', '.join(marked[:-1])}, но {marked[-1]}?"


def walk(topic: str, *, words=None, seed: int | None = None) -> dict | None:
    """The topic's walk for the page, or None when it has none."""
    from .lessontext import WALKS

    spec = WALKS.get(topic)
    if spec is None:
        return None
    seed = secrets.randbelow(2**31) if seed is None else seed

    notice = [s for s in (sentence(topic, x) for x in spec.notice) if s]
    forms = list(dict.fromkeys(s["form"] for s in notice))
    contrast = [c | {"id": spec_c.id, "et": spec_c.et, "ru": spec_c.ru}
                for spec_c in spec.contrast
                if (c := sentence(topic, spec_c.sentence)) and c.get("wrong")]
    switch = [c | {"id": spec_c.id, "et": spec_c.et, "ru": spec_c.ru}
              for spec_c in spec.switch
              if (c := sentence(topic, spec_c.sentence))]
    built = [*notice, *contrast, *switch]
    quoted = sorted({s["source"] for s in built if s["source"]})
    return {
        "topic": topic,
        "notice": {
            # Not yet named: the learner tries first (DESIGN.md, Principles).
            "examples": [{k: v for k, v in s.items()
                          if k not in ("name", "form_ru", "wrong", "wrong_tag")}
                         for s in notice] if len(forms) >= 2 else [],
            "question_ru": _question(forms) if len(forms) >= 2 else "",
        },
        "ask": {"items": _ask(topic, spec.ask, seed, words)},
        "explain": _explain(topic, spec, built),
        "contrast": contrast,
        "switch": {"conditions": switch if len(switch) >= 2 else []},
        "quoted": quoted,
    }
